<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.test.CNHi.testSuite.TestPlan" tests="1" time="73.128" ignored="8" failures="1" timestamp="09 Aug 2018 13:55:38 GMT" skipped="0" hostname="LIN17000597" errors="0">
  <testcase name="CNHiRestAssured_GETTest" time="73.128" classname="com.test.CNHi.testSuite.TestPlan">
    <failure type="java.lang.AssertionError" message="[printTestSummary] Testcase &#039;CNHiRestAssured_GETTest &#039; FAILED.">
      <![CDATA[java.lang.AssertionError: [printTestSummary] Testcase 'CNHiRestAssured_GETTest ' FAILED.
	at org.testng.Assert.fail(Assert.java:94)
	at com.htap.fw_core.FW_BaseTestCase.printTestSummary(FW_BaseTestCase.java:318)
	at com.test.CNHi.testSuite.TestPlan.CNHiRestAssured_GETTest(TestPlan.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.TestNG.privateMain(TestNG.java:1434)
	at org.testng.TestNG.main(TestNG.java:1403)
]]>
    </failure>
  </testcase> <!-- CNHiRestAssured_GETTest -->
  <testcase name="EVOFleetHomeScreenTest" classname="com.test.CNHi.testSuite.TestPlan">
    <skipped/>
  </testcase> <!-- EVOFleetHomeScreenTest -->
  <testcase name="CNHiFarmAPPFieldTestUserA" classname="com.test.CNHi.testSuite.TestPlan">
    <skipped/>
  </testcase> <!-- CNHiFarmAPPFieldTestUserA -->
  <testcase name="CNHiFleetAPPLoginTest_Android2" classname="com.test.CNHi.testSuite.TestPlan">
    <skipped/>
  </testcase> <!-- CNHiFleetAPPLoginTest_Android2 -->
  <testcase name="CNHiFarmAPPFieldTestUserC" classname="com.test.CNHi.testSuite.TestPlan">
    <skipped/>
  </testcase> <!-- CNHiFarmAPPFieldTestUserC -->
  <testcase name="CNHiFleetWebAPPLoginTest" classname="com.test.CNHi.testSuite.TestPlan">
    <skipped/>
  </testcase> <!-- CNHiFleetWebAPPLoginTest -->
  <testcase name="CNHiFarmAPPFieldTestUserB" classname="com.test.CNHi.testSuite.TestPlan">
    <skipped/>
  </testcase> <!-- CNHiFarmAPPFieldTestUserB -->
  <testcase name="CNHiFarmAPPVehicleStatusTest" classname="com.test.CNHi.testSuite.TestPlan">
    <skipped/>
  </testcase> <!-- CNHiFarmAPPVehicleStatusTest -->
  <testcase name="CNHiFleetAPPLoginTest_Android" classname="com.test.CNHi.testSuite.TestPlan">
    <skipped/>
  </testcase> <!-- CNHiFleetAPPLoginTest_Android -->
</testsuite> <!-- com.test.CNHi.testSuite.TestPlan -->
