<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="8" total="9" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="CNHi_TestSuite" duration-ms="73159" started-at="2018-08-09T13:54:24Z" finished-at="2018-08-09T13:55:38Z">
    <groups>
      <group name="CNHiRestAssured_GETTest">
        <method signature="TestPlan.CNHiRestAssured_GETTest()[pri:0, instance:com.test.CNHi.testSuite.TestPlan@1bce4f0a]" name="CNHiRestAssured_GETTest" class="com.test.CNHi.testSuite.TestPlan"/>
      </group> <!-- CNHiRestAssured_GETTest -->
    </groups>
    <test name="CNHiAPTTest_Restful" duration-ms="73159" started-at="2018-08-09T13:54:24Z" finished-at="2018-08-09T13:55:38Z">
      <class name="com.test.CNHi.testSuite.TestPlan">
        <test-method status="PASS" signature="testplanEnter()[pri:0, instance:com.test.CNHi.testSuite.TestPlan@1bce4f0a]" name="testplanEnter" is-config="true" duration-ms="15" started-at="2018-08-09T19:24:24Z" finished-at="2018-08-09T19:24:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testplanEnter -->
        <test-method status="PASS" signature="testcaseEnter(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.CNHi.testSuite.TestPlan@1bce4f0a]" name="testcaseEnter" is-config="true" duration-ms="16" started-at="2018-08-09T19:24:24Z" finished-at="2018-08-09T19:24:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[WINDOWS]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[API]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[APIAPP]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Not Required]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcaseEnter -->
        <test-method status="FAIL" signature="CNHiRestAssured_GETTest()[pri:0, instance:com.test.CNHi.testSuite.TestPlan@1bce4f0a]" name="CNHiRestAssured_GETTest" duration-ms="73112" started-at="2018-08-09T19:24:24Z" description="Rest Assured api test" finished-at="2018-08-09T19:25:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[printTestSummary] Testcase 'CNHiRestAssured_GETTest ' FAILED.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [printTestSummary] Testcase 'CNHiRestAssured_GETTest ' FAILED.
	at org.testng.Assert.fail(Assert.java:94)
	at com.htap.fw_core.FW_BaseTestCase.printTestSummary(FW_BaseTestCase.java:318)
	at com.test.CNHi.testSuite.TestPlan.CNHiRestAssured_GETTest(TestPlan.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.TestNG.privateMain(TestNG.java:1434)
	at org.testng.TestNG.main(TestNG.java:1403)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CNHiRestAssured_GETTest -->
        <test-method status="PASS" signature="testcaseExit()[pri:0, instance:com.test.CNHi.testSuite.TestPlan@1bce4f0a]" name="testcaseExit" is-config="true" duration-ms="0" started-at="2018-08-09T19:25:38Z" finished-at="2018-08-09T19:25:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcaseExit -->
        <test-method status="PASS" signature="testplanExit()[pri:0, instance:com.test.CNHi.testSuite.TestPlan@1bce4f0a]" name="testplanExit" is-config="true" duration-ms="16" started-at="2018-08-09T19:25:38Z" finished-at="2018-08-09T19:25:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testplanExit -->
      </class> <!-- com.test.CNHi.testSuite.TestPlan -->
    </test> <!-- CNHiAPTTest_Restful -->
  </suite> <!-- CNHi_TestSuite -->
</testng-results>
